import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './nav'
import Footer from './footer'
const inter = Inter({ subsets: ['latin'] })
import NextTopLoader from 'nextjs-toploader'
import '@fortawesome/fontawesome-free/css/all.min.css';


export const metadata: Metadata = {
  title: 'Movies App',
  description: 'Generated by amine diouane',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader 
        color="#facc15"

      />
        
     <Navbar/>
      {children}
      <Footer />
      </body>
    </html>
  )
}
