import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'dashbord',
    description: 'Generated by amine diouane',
  }


export default function Layout({children} : {children: React.ReactNode}) {
    return (
        <div>
        {/* <h1>Layout dashbord</h1> */}
        {children}
        </div>
    );
}